#!/bin/bash

# midi connect
( /bin/sleep 10; /usr/bin/aconnect 24:0 128:0; /usr/bin/aconnect 128:2 24:0; ) &

# gba serial watcher
./gba-sync-serial.py &
gbapid=$!

if [ "$1" != "--gui" ]
then
  guiflag="-nogui"
else
  guiflag=""
fi

/usr/bin/pd $guiflag -alsamidi -mididev 0,1 _main.pd &
pdpid=$!

# trap exit and kill daemons
trap "kill $pdpid; kill $gbapid; trap - SIGTERM; exit" SIGTERM SIGINT EXIT

wait "$pdpid"
